### ISSUE TITLE
Syntax Changes in JSON Schema

### ISSUE THREAD

**Issue by PythooonUser** [martinring/tmlanguage#13]
There have been some syntax changes in the JSON schema and now the tmLanguage schema is invalid, which leads to something like the following:

```yaml
repository:
  comment:
    patterns:
      - name: "comment.block.cs"
        begin: "/\\*"
        end: "\\*/"
```

This produces an error:
> Incorrect type. Expected "end | while".

But the above schema is correct.
